name: Deploy to Endora via SFTP

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "23.x"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server:   ${{ secrets.FTP_SERVER }}     # 185.102.21.10
          port:     222                           # SFTP port podľa Endory
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath:  dist/*
          remotePath: /web/                       # koreň webu
