name: Deploy to Endora (FTP)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}     # 185.102.21.10
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp                         # <-- FTP (nie sftp, nie ftps)
          port: 21
          local-dir: dist/                      # uploaduje obsah buildu
          server-dir: public_html/              # pri FTP je docroot zvyčajne public_html/
          # dangerous-clean-slate: true         # voliteľne: vymaže cieľ pred uploadom
